### ISSUE TITLE
set up basic unit and integration tests

### ISSUE THREAD

**Issue by drenalin23** [mmi-cookbooks/metrics-repose#31]
## Description
We need a basic set of units and integration tests.  Goal is to allow developers to add more detailed unit tests when they work on this wrapper cookbook.
Use chefspec for unit tests and serverspec for integration tests.

## Todo
- [x] add or update kitchen.yml configuration with ingest and query suites
- [x] add or update travis.yml configuration using docker to run multiple test suites
- [x] update Rakefile to add rubocop and foodcritic testing (and add to travis)
- [x] Add unit tests for wadl files creation
- [x] Add unit tests for wrapper cookbook related resources
- [x] add integration tests for ingest and query roles

## How to test
Make sure that travis suite passes.

## Acceptance Criteria
A set of unit and integration tests that can be run locally via rake tasks and are run in travisCI when new PRs are submitted.

## References
The metrics-filebeat repository has a good test framework as a reference.
